// Copyright 2021 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: osv_service_v1.proto

package v1

import (
	models "github.com/google/osv.dev/go/internal/models"
	osvschema "github.com/ossf/osv-schema/bindings/go/osvschema"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileHash_HashType int32

const (
	FileHash_MD5 FileHash_HashType = 0
)

// Enum value maps for FileHash_HashType.
var (
	FileHash_HashType_name = map[int32]string{
		0: "MD5",
	}
	FileHash_HashType_value = map[string]int32{
		"MD5": 0,
	}
)

func (x FileHash_HashType) Enum() *FileHash_HashType {
	p := new(FileHash_HashType)
	*p = x
	return p
}

func (x FileHash_HashType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileHash_HashType) Descriptor() protoreflect.EnumDescriptor {
	return file_osv_service_v1_proto_enumTypes[0].Descriptor()
}

func (FileHash_HashType) Type() protoreflect.EnumType {
	return &file_osv_service_v1_proto_enumTypes[0]
}

func (x FileHash_HashType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileHash_HashType.Descriptor instead.
func (FileHash_HashType) EnumDescriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{10, 0}
}

type VersionRepositoryInformation_RepoType int32

const (
	VersionRepositoryInformation_UNSPECIFIED VersionRepositoryInformation_RepoType = 0
	VersionRepositoryInformation_GIT         VersionRepositoryInformation_RepoType = 1
)

// Enum value maps for VersionRepositoryInformation_RepoType.
var (
	VersionRepositoryInformation_RepoType_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "GIT",
	}
	VersionRepositoryInformation_RepoType_value = map[string]int32{
		"UNSPECIFIED": 0,
		"GIT":         1,
	}
)

func (x VersionRepositoryInformation_RepoType) Enum() *VersionRepositoryInformation_RepoType {
	p := new(VersionRepositoryInformation_RepoType)
	*p = x
	return p
}

func (x VersionRepositoryInformation_RepoType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionRepositoryInformation_RepoType) Descriptor() protoreflect.EnumDescriptor {
	return file_osv_service_v1_proto_enumTypes[1].Descriptor()
}

func (VersionRepositoryInformation_RepoType) Type() protoreflect.EnumType {
	return &file_osv_service_v1_proto_enumTypes[1]
}

func (x VersionRepositoryInformation_RepoType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VersionRepositoryInformation_RepoType.Descriptor instead.
func (VersionRepositoryInformation_RepoType) EnumDescriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{14, 0}
}

// A list of Vulnerability entries.
type VulnerabilityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vulns         []*osvschema.Vulnerability `protobuf:"bytes,1,rep,name=vulns,proto3" json:"vulns,omitempty"`
	NextPageToken string                     `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
}

func (x *VulnerabilityList) Reset() {
	*x = VulnerabilityList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VulnerabilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VulnerabilityList) ProtoMessage() {}

func (x *VulnerabilityList) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VulnerabilityList.ProtoReflect.Descriptor instead.
func (*VulnerabilityList) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{0}
}

func (x *VulnerabilityList) GetVulns() []*osvschema.Vulnerability {
	if x != nil {
		return x.Vulns
	}
	return nil
}

func (x *VulnerabilityList) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// Batched lists of Vulnerability entries.
type BatchVulnerabilityList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*VulnerabilityList `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *BatchVulnerabilityList) Reset() {
	*x = BatchVulnerabilityList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchVulnerabilityList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchVulnerabilityList) ProtoMessage() {}

func (x *BatchVulnerabilityList) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchVulnerabilityList.ProtoReflect.Descriptor instead.
func (*BatchVulnerabilityList) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{1}
}

func (x *BatchVulnerabilityList) GetResults() []*VulnerabilityList {
	if x != nil {
		return x.Results
	}
	return nil
}

// Query format.
type Query struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Param:
	//
	//	*Query_Commit
	//	*Query_Version
	Param isQuery_Param `protobuf_oneof:"param"`
	// The package to query against. When a `commit` hash is given, this is
	// optional.
	Package   *osvschema.Package `protobuf:"bytes,4,opt,name=package,proto3" json:"package,omitempty"`
	PageToken string             `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}

func (x *Query) Reset() {
	*x = Query{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{2}
}

func (m *Query) GetParam() isQuery_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (x *Query) GetCommit() string {
	if x, ok := x.GetParam().(*Query_Commit); ok {
		return x.Commit
	}
	return ""
}

func (x *Query) GetVersion() string {
	if x, ok := x.GetParam().(*Query_Version); ok {
		return x.Version
	}
	return ""
}

func (x *Query) GetPackage() *osvschema.Package {
	if x != nil {
		return x.Package
	}
	return nil
}

func (x *Query) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type isQuery_Param interface {
	isQuery_Param()
}

type Query_Commit struct {
	// The commit hash to query for. If specified, `version` should not be set.
	Commit string `protobuf:"bytes,1,opt,name=commit,proto3,oneof"`
}

type Query_Version struct {
	// The version string to query for. A fuzzy match is done against upstream
	// versions. If specified, `commit` should not be set.
	Version string `protobuf:"bytes,2,opt,name=version,proto3,oneof"`
}

func (*Query_Commit) isQuery_Param() {}

func (*Query_Version) isQuery_Param() {}

// Batch query format.
type BatchQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The queries that form this batch query.
	Queries []*Query `protobuf:"bytes,1,rep,name=queries,proto3" json:"queries,omitempty"`
}

func (x *BatchQuery) Reset() {
	*x = BatchQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchQuery) ProtoMessage() {}

func (x *BatchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchQuery.ProtoReflect.Descriptor instead.
func (*BatchQuery) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{3}
}

func (x *BatchQuery) GetQueries() []*Query {
	if x != nil {
		return x.Queries
	}
	return nil
}

// Parameters for GetBugById.
type GetVulnByIdParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetVulnByIdParameters) Reset() {
	*x = GetVulnByIdParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVulnByIdParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVulnByIdParameters) ProtoMessage() {}

func (x *GetVulnByIdParameters) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVulnByIdParameters.ProtoReflect.Descriptor instead.
func (*GetVulnByIdParameters) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{4}
}

func (x *GetVulnByIdParameters) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Parameters for QueryAffected.
type QueryAffectedParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *Query `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryAffectedParameters) Reset() {
	*x = QueryAffectedParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAffectedParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAffectedParameters) ProtoMessage() {}

func (x *QueryAffectedParameters) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAffectedParameters.ProtoReflect.Descriptor instead.
func (*QueryAffectedParameters) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{5}
}

func (x *QueryAffectedParameters) GetQuery() *Query {
	if x != nil {
		return x.Query
	}
	return nil
}

// Parameters for QueryAffectedBatch.
type QueryAffectedBatchParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *BatchQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *QueryAffectedBatchParameters) Reset() {
	*x = QueryAffectedBatchParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAffectedBatchParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAffectedBatchParameters) ProtoMessage() {}

func (x *QueryAffectedBatchParameters) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAffectedBatchParameters.ProtoReflect.Descriptor instead.
func (*QueryAffectedBatchParameters) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{6}
}

func (x *QueryAffectedBatchParameters) GetQuery() *BatchQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// Parameters for DetermineVersion.
type DetermineVersionParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query *VersionQuery `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
}

func (x *DetermineVersionParameters) Reset() {
	*x = DetermineVersionParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetermineVersionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetermineVersionParameters) ProtoMessage() {}

func (x *DetermineVersionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetermineVersionParameters.ProtoReflect.Descriptor instead.
func (*DetermineVersionParameters) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{7}
}

func (x *DetermineVersionParameters) GetQuery() *VersionQuery {
	if x != nil {
		return x.Query
	}
	return nil
}

// Parameters for ImportFindings.
type ImportFindingsParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
}

func (x *ImportFindingsParameters) Reset() {
	*x = ImportFindingsParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportFindingsParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFindingsParameters) ProtoMessage() {}

func (x *ImportFindingsParameters) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFindingsParameters.ProtoReflect.Descriptor instead.
func (*ImportFindingsParameters) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ImportFindingsParameters) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// The version query.
type VersionQuery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The name of the dependency. Can be empty.
	Name       string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FileHashes []*FileHash `protobuf:"bytes,2,rep,name=file_hashes,json=fileHashes,proto3" json:"file_hashes,omitempty"`
}

func (x *VersionQuery) Reset() {
	*x = VersionQuery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionQuery) ProtoMessage() {}

func (x *VersionQuery) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionQuery.ProtoReflect.Descriptor instead.
func (*VersionQuery) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{9}
}

func (x *VersionQuery) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VersionQuery) GetFileHashes() []*FileHash {
	if x != nil {
		return x.FileHashes
	}
	return nil
}

// Information about the files in the repository
// to identify the version.
type FileHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The file path inside the repository, relative to the repository root.
	FilePath string            `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	HashType FileHash_HashType `protobuf:"varint,2,opt,name=hash_type,json=hashType,proto3,enum=osv.v1.FileHash_HashType" json:"hash_type,omitempty"`
	Hash     []byte            `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *FileHash) Reset() {
	*x = FileHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileHash) ProtoMessage() {}

func (x *FileHash) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileHash.ProtoReflect.Descriptor instead.
func (*FileHash) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{10}
}

func (x *FileHash) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *FileHash) GetHashType() FileHash_HashType {
	if x != nil {
		return x.HashType
	}
	return FileHash_MD5
}

func (x *FileHash) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

// Result of DetmineVersion.
type VersionMatchList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Matches []*VersionMatch `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
}

func (x *VersionMatchList) Reset() {
	*x = VersionMatchList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionMatchList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMatchList) ProtoMessage() {}

func (x *VersionMatchList) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMatchList.ProtoReflect.Descriptor instead.
func (*VersionMatchList) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{11}
}

func (x *VersionMatchList) GetMatches() []*VersionMatch {
	if x != nil {
		return x.Matches
	}
	return nil
}

// Result of ImportFindings.
type ImportFindingList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InvalidRecords []*models.ImportFinding `protobuf:"bytes,1,rep,name=invalid_records,json=invalidRecords,proto3" json:"invalid_records,omitempty"`
}

func (x *ImportFindingList) Reset() {
	*x = ImportFindingList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportFindingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportFindingList) ProtoMessage() {}

func (x *ImportFindingList) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportFindingList.ProtoReflect.Descriptor instead.
func (*ImportFindingList) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ImportFindingList) GetInvalidRecords() []*models.ImportFinding {
	if x != nil {
		return x.InvalidRecords
	}
	return nil
}

// Match information for the provided VersionQuery.
type VersionMatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Score in the interval (0.0, 1.0] with 1.0 being a perfect match.
	Score float64 `protobuf:"fixed64,1,opt,name=score,proto3" json:"score,omitempty"`
	// Information about the upstream repository.
	RepoInfo *VersionRepositoryInformation `protobuf:"bytes,2,opt,name=repo_info,json=repoInfo,proto3" json:"repo_info,omitempty"`
	// The OSV identifier.
	OsvIdentifier *osvschema.Package `protobuf:"bytes,3,opt,name=osv_identifier,json=osvIdentifier,proto3" json:"osv_identifier,omitempty"`
	// CPE 2.3.
	Cpe23 string `protobuf:"bytes,5,opt,name=cpe23,proto3" json:"cpe23,omitempty"`
	// Definite number of files that have matched.
	MinimumFileMatches int64 `protobuf:"varint,6,opt,name=minimum_file_matches,json=minimumFileMatches,proto3" json:"minimum_file_matches,omitempty"`
	// Estimated number of files that are different.
	EstimatedDiffFiles int64 `protobuf:"varint,7,opt,name=estimated_diff_files,json=estimatedDiffFiles,proto3" json:"estimated_diff_files,omitempty"`
}

func (x *VersionMatch) Reset() {
	*x = VersionMatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionMatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionMatch) ProtoMessage() {}

func (x *VersionMatch) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionMatch.ProtoReflect.Descriptor instead.
func (*VersionMatch) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{13}
}

func (x *VersionMatch) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *VersionMatch) GetRepoInfo() *VersionRepositoryInformation {
	if x != nil {
		return x.RepoInfo
	}
	return nil
}

func (x *VersionMatch) GetOsvIdentifier() *osvschema.Package {
	if x != nil {
		return x.OsvIdentifier
	}
	return nil
}

func (x *VersionMatch) GetCpe23() string {
	if x != nil {
		return x.Cpe23
	}
	return ""
}

func (x *VersionMatch) GetMinimumFileMatches() int64 {
	if x != nil {
		return x.MinimumFileMatches
	}
	return 0
}

func (x *VersionMatch) GetEstimatedDiffFiles() int64 {
	if x != nil {
		return x.EstimatedDiffFiles
	}
	return 0
}

type VersionRepositoryInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type VersionRepositoryInformation_RepoType `protobuf:"varint,1,opt,name=type,proto3,enum=osv.v1.VersionRepositoryInformation_RepoType" json:"type,omitempty"`
	// Source address of the repository.
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// Commit tag
	Tag string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	// Parsed version from commit tag
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	// Commit hash hex.
	Commit string `protobuf:"bytes,6,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *VersionRepositoryInformation) Reset() {
	*x = VersionRepositoryInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_osv_service_v1_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VersionRepositoryInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRepositoryInformation) ProtoMessage() {}

func (x *VersionRepositoryInformation) ProtoReflect() protoreflect.Message {
	mi := &file_osv_service_v1_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionRepositoryInformation.ProtoReflect.Descriptor instead.
func (*VersionRepositoryInformation) Descriptor() ([]byte, []int) {
	return file_osv_service_v1_proto_rawDescGZIP(), []int{14}
}

func (x *VersionRepositoryInformation) GetType() VersionRepositoryInformation_RepoType {
	if x != nil {
		return x.Type
	}
	return VersionRepositoryInformation_UNSPECIFIED
}

func (x *VersionRepositoryInformation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VersionRepositoryInformation) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VersionRepositoryInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *VersionRepositoryInformation) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

var File_osv_service_v1_proto protoreflect.FileDescriptor

var file_osv_service_v1_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6f, 0x73, 0x76, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x76, 0x31,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x1a, 0x17,
	0x6f, 0x73, 0x76, 0x2f, 0x76, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x6f, 0x73, 0x76, 0x2f, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x66, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65,
	0x0a, 0x11, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x75, 0x6c, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x05, 0x76, 0x75, 0x6c, 0x6e, 0x73, 0x12, 0x26, 0x0a,
	0x0f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4d, 0x0a, 0x16, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x75,
	0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x33, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72,
	0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x05, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x18,
	0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x1a, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x52, 0x07, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x61, 0x67, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x70, 0x61, 0x67, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x70,
	0x61, 0x72, 0x61, 0x6d, 0x22, 0x35, 0x0a, 0x0a, 0x42, 0x61, 0x74, 0x63, 0x68, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x12, 0x27, 0x0a, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x52, 0x07, 0x71, 0x75, 0x65, 0x72, 0x69, 0x65, 0x73, 0x22, 0x27, 0x0a, 0x15, 0x47,
	0x65, 0x74, 0x56, 0x75, 0x6c, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12,
	0x23, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x22, 0x48, 0x0a, 0x1c, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x66, 0x66,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x28, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x48,
	0x0a, 0x1a, 0x44, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x12, 0x2a, 0x0a, 0x05,
	0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x73,
	0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x52, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x22, 0x32, 0x0a, 0x18, 0x49, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x55, 0x0a, 0x0c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x31, 0x0a, 0x0b, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68, 0x52, 0x0a, 0x66, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73,
	0x68, 0x65, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x36, 0x0a,
	0x09, 0x68, 0x61, 0x73, 0x68, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x19, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x48, 0x61,
	0x73, 0x68, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x68, 0x61, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x13, 0x0a, 0x08, 0x48, 0x61, 0x73,
	0x68, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x10, 0x00, 0x22, 0x42,
	0x0a, 0x10, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x2e, 0x0a, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x07, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x73, 0x22, 0x50, 0x0a, 0x11, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3b, 0x0a, 0x0f, 0x69, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x0e, 0x69, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x73, 0x22, 0x96, 0x02, 0x0a, 0x0c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x41, 0x0a, 0x09, 0x72,
	0x65, 0x70, 0x6f, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x72, 0x65, 0x70, 0x6f, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x33,
	0x0a, 0x0e, 0x6f, 0x73, 0x76, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x52, 0x0d, 0x6f, 0x73, 0x76, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x70, 0x65, 0x32, 0x33, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x70, 0x65, 0x32, 0x33, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x69, 0x6e,
	0x69, 0x6d, 0x75, 0x6d, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d,
	0x46, 0x69, 0x6c, 0x65, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x30, 0x0a, 0x14, 0x65,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x64, 0x69, 0x66, 0x66, 0x5f, 0x66, 0x69,
	0x6c, 0x65, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x12, 0x65, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x64, 0x44, 0x69, 0x66, 0x66, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x22, 0xe5, 0x01,
	0x0a, 0x1c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x41,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2d, 0x2e, 0x6f,
	0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x74,
	0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x18, 0x0a,
	0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22,
	0x24, 0x0a, 0x08, 0x52, 0x65, 0x70, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0f, 0x0a, 0x0b, 0x55,
	0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x47, 0x49, 0x54, 0x10, 0x01, 0x32, 0xc5, 0x04, 0x0a, 0x03, 0x4f, 0x53, 0x56, 0x12, 0x58, 0x0a,
	0x0b, 0x47, 0x65, 0x74, 0x56, 0x75, 0x6c, 0x6e, 0x42, 0x79, 0x49, 0x64, 0x12, 0x1d, 0x2e, 0x6f,
	0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x75, 0x6c, 0x6e, 0x42, 0x79, 0x49,
	0x64, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x12, 0x2e, 0x6f, 0x73,
	0x76, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x22,
	0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10, 0x12, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x75, 0x6c,
	0x6e, 0x73, 0x2f, 0x7b, 0x69, 0x64, 0x7d, 0x12, 0x65, 0x0a, 0x0d, 0x51, 0x75, 0x65, 0x72, 0x79,
	0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x1f, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76,
	0x31, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x19, 0x2e, 0x6f, 0x73, 0x76, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x18, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x12, 0x22, 0x09, 0x2f, 0x76,
	0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x3a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x79,
	0x0a, 0x12, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x24, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x51, 0x75,
	0x65, 0x72, 0x79, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x1e, 0x2e, 0x6f, 0x73, 0x76,
	0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x56, 0x75, 0x6c, 0x6e, 0x65, 0x72, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x17, 0x22, 0x0e, 0x2f, 0x76, 0x31, 0x2f, 0x71, 0x75, 0x65, 0x72, 0x79, 0x62, 0x61, 0x74,
	0x63, 0x68, 0x3a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x81, 0x01, 0x0a, 0x10, 0x44, 0x65,
	0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22,
	0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e,
	0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65,
	0x72, 0x73, 0x1a, 0x18, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x29, 0x22, 0x20, 0x2f, 0x76, 0x31, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x65, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x3a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x7e, 0x0a,
	0x0e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12,
	0x20, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x46,
	0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x1a, 0x19, 0x2e, 0x6f, 0x73, 0x76, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x46, 0x69, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x2f, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x29, 0x12, 0x27, 0x2f, 0x76, 0x31, 0x65, 0x78, 0x70, 0x65, 0x72, 0x69, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x6c, 0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x66, 0x69, 0x6e, 0x64,
	0x69, 0x6e, 0x67, 0x73, 0x2f, 0x7b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x7d, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x6f, 0x73, 0x76, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x6b,
	0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6f, 0x73, 0x76, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_osv_service_v1_proto_rawDescOnce sync.Once
	file_osv_service_v1_proto_rawDescData = file_osv_service_v1_proto_rawDesc
)

func file_osv_service_v1_proto_rawDescGZIP() []byte {
	file_osv_service_v1_proto_rawDescOnce.Do(func() {
		file_osv_service_v1_proto_rawDescData = protoimpl.X.CompressGZIP(file_osv_service_v1_proto_rawDescData)
	})
	return file_osv_service_v1_proto_rawDescData
}

var file_osv_service_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_osv_service_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_osv_service_v1_proto_goTypes = []interface{}{
	(FileHash_HashType)(0),                     // 0: osv.v1.FileHash.HashType
	(VersionRepositoryInformation_RepoType)(0), // 1: osv.v1.VersionRepositoryInformation.RepoType
	(*VulnerabilityList)(nil),                  // 2: osv.v1.VulnerabilityList
	(*BatchVulnerabilityList)(nil),             // 3: osv.v1.BatchVulnerabilityList
	(*Query)(nil),                              // 4: osv.v1.Query
	(*BatchQuery)(nil),                         // 5: osv.v1.BatchQuery
	(*GetVulnByIdParameters)(nil),              // 6: osv.v1.GetVulnByIdParameters
	(*QueryAffectedParameters)(nil),            // 7: osv.v1.QueryAffectedParameters
	(*QueryAffectedBatchParameters)(nil),       // 8: osv.v1.QueryAffectedBatchParameters
	(*DetermineVersionParameters)(nil),         // 9: osv.v1.DetermineVersionParameters
	(*ImportFindingsParameters)(nil),           // 10: osv.v1.ImportFindingsParameters
	(*VersionQuery)(nil),                       // 11: osv.v1.VersionQuery
	(*FileHash)(nil),                           // 12: osv.v1.FileHash
	(*VersionMatchList)(nil),                   // 13: osv.v1.VersionMatchList
	(*ImportFindingList)(nil),                  // 14: osv.v1.ImportFindingList
	(*VersionMatch)(nil),                       // 15: osv.v1.VersionMatch
	(*VersionRepositoryInformation)(nil),       // 16: osv.v1.VersionRepositoryInformation
	(*osvschema.Vulnerability)(nil),            // 17: osv.Vulnerability
	(*osvschema.Package)(nil),                  // 18: osv.Package
	(*models.ImportFinding)(nil),               // 19: osv.ImportFinding
}
var file_osv_service_v1_proto_depIdxs = []int32{
	17, // 0: osv.v1.VulnerabilityList.vulns:type_name -> osv.Vulnerability
	2,  // 1: osv.v1.BatchVulnerabilityList.results:type_name -> osv.v1.VulnerabilityList
	18, // 2: osv.v1.Query.package:type_name -> osv.Package
	4,  // 3: osv.v1.BatchQuery.queries:type_name -> osv.v1.Query
	4,  // 4: osv.v1.QueryAffectedParameters.query:type_name -> osv.v1.Query
	5,  // 5: osv.v1.QueryAffectedBatchParameters.query:type_name -> osv.v1.BatchQuery
	11, // 6: osv.v1.DetermineVersionParameters.query:type_name -> osv.v1.VersionQuery
	12, // 7: osv.v1.VersionQuery.file_hashes:type_name -> osv.v1.FileHash
	0,  // 8: osv.v1.FileHash.hash_type:type_name -> osv.v1.FileHash.HashType
	15, // 9: osv.v1.VersionMatchList.matches:type_name -> osv.v1.VersionMatch
	19, // 10: osv.v1.ImportFindingList.invalid_records:type_name -> osv.ImportFinding
	16, // 11: osv.v1.VersionMatch.repo_info:type_name -> osv.v1.VersionRepositoryInformation
	18, // 12: osv.v1.VersionMatch.osv_identifier:type_name -> osv.Package
	1,  // 13: osv.v1.VersionRepositoryInformation.type:type_name -> osv.v1.VersionRepositoryInformation.RepoType
	6,  // 14: osv.v1.OSV.GetVulnById:input_type -> osv.v1.GetVulnByIdParameters
	7,  // 15: osv.v1.OSV.QueryAffected:input_type -> osv.v1.QueryAffectedParameters
	8,  // 16: osv.v1.OSV.QueryAffectedBatch:input_type -> osv.v1.QueryAffectedBatchParameters
	9,  // 17: osv.v1.OSV.DetermineVersion:input_type -> osv.v1.DetermineVersionParameters
	10, // 18: osv.v1.OSV.ImportFindings:input_type -> osv.v1.ImportFindingsParameters
	17, // 19: osv.v1.OSV.GetVulnById:output_type -> osv.Vulnerability
	2,  // 20: osv.v1.OSV.QueryAffected:output_type -> osv.v1.VulnerabilityList
	3,  // 21: osv.v1.OSV.QueryAffectedBatch:output_type -> osv.v1.BatchVulnerabilityList
	13, // 22: osv.v1.OSV.DetermineVersion:output_type -> osv.v1.VersionMatchList
	14, // 23: osv.v1.OSV.ImportFindings:output_type -> osv.v1.ImportFindingList
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_osv_service_v1_proto_init() }
func file_osv_service_v1_proto_init() {
	if File_osv_service_v1_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_osv_service_v1_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VulnerabilityList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchVulnerabilityList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Query); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BatchQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVulnByIdParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAffectedParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAffectedBatchParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetermineVersionParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportFindingsParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionQuery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionMatchList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportFindingList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionMatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_osv_service_v1_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VersionRepositoryInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_osv_service_v1_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Query_Commit)(nil),
		(*Query_Version)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_osv_service_v1_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_osv_service_v1_proto_goTypes,
		DependencyIndexes: file_osv_service_v1_proto_depIdxs,
		EnumInfos:         file_osv_service_v1_proto_enumTypes,
		MessageInfos:      file_osv_service_v1_proto_msgTypes,
	}.Build()
	File_osv_service_v1_proto = out.File
	file_osv_service_v1_proto_rawDesc = nil
	file_osv_service_v1_proto_goTypes = nil
	file_osv_service_v1_proto_depIdxs = nil
}
